services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means

    Aropixel\MenuBundle\:
        resource: '../../*'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../AropixelMenuBundle.php'
            - '../../Resources/'

    Aropixel\MenuBundle\Controller\:
        resource: '../../Controller'
        tags: [ 'controller.service_arguments' ]

    Aropixel\MenuBundle\MenuHandler\MenuManager:
        public: true
        autowire: true
